name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Bun modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Build project
        run: bun run build
